### ISSUE TITLE
Boxstring

### ISSUE THREAD

**Issue by psaunders** [turbulent/substance#12]
Boxstring is not obvious, would be good if the substance box ls echoed a boxstring after the hash

![simp_5_1024x1024](https://user-images.githubusercontent.com/424956/30073670-a370620e-923c-11e7-9755-72d9fa960c3e.jpg)

**Comment by bbeausej** [comment]
I'm not sure I follow this issue. At what stage would it be useful to output the list of boxes?
After creation?
