### ISSUE TITLE
Box Engine CLI

### ISSUE THREAD

**Issue by psaunders** [turbulent/substance#13]
If you delete an engine and then try to create a new one you'll get a:
```
box 'oldboxname' does not exist
```

Until you close that terminal session (on OSX at least)

**Comment by bbeausej** [comment]
Ah! Seems to be a problem with the local db. Some records seem doubled up.

-b

**Comment by Kiniamaro** [comment]
This doesn't seem to cause any issues on my setup (arch linux). Was this fixed and someone forgot to close the issue?

**Comment by bbeausej** [comment]
No it's still opened. The local db handler doubles up the records in the local db.
We might have fixed the crash error ; but the doubling up is still present.

-b

**Comment by bbeausej** [comment]
Fixed in #40
