### ISSUE TITLE
add aliases in subenv.yml

### ISSUE THREAD

**Issue by Kiniamaro** [turbulent/substance#22]
It would be very helpful if users could add custom aliases inside their `.substance/subenv.yml`. This would make it so users aren't required to go manually add aliases inside their `engine.yml` and repo owners can easily define special aliases to meet their specific needs.

**Comment by Kiniamaro** [comment]
Turns out you can do something similar using dockwrkr jobs. however I still think it could be an interesting feature overall.

**Comment by bbeausej** [comment]
Totally, we had initially planned for this so you could have global and per-engine aliases.

Having global aliases can be super useful for environment setups where more than one subenv share container names and commands.
