### ISSUE TITLE
Upgrade to python 3.6

### ISSUE THREAD

**Issue by Kiniamaro** [turbulent/substance#27]
I feel like this is kind of self explanatory. Python 2.7 is legacy, granted still widely used but it's on the way out. Python3 makes python just a more consistent language while adding in some cool new useful features.

as for the upgrade itself, it's usually not that time consuming. someone familiar with python could do it in a day _*(ESTIMATE)*_ with relatively little road blocks.

**Comment by bbeausej** [comment]
Fixed in #40
